In [ ]:
import numpy as np
from scipy.sparse import diags
from scipy.linalg import norm
from scipy.sparse.linalg import bicg

In [ ]:
A = np.array([
[2.001,1,1,1,1,1],
[1,2.001,1,1,4.999,1],
[1,1,1,2.001,1,1],
[1,1,1,1,2.001,1],
[0.001,1,1,1,1,2.001],
[0.001,1,1,1,1,2.001]
])

print('Shape of matrix A:',A.shape)
print()
A

Shape of matrix A: (6, 6)



array([[2.001e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 2.001e+00, 1.000e+00, 1.000e+00, 4.999e+00, 1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 2.001e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.001e+00, 1.000e+00],
       [1.000e-03, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.001e+00],
       [1.000e-03, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.001e+00]])

In [ ]:
print('condition number of matrix A is :',np.linalg.cond(A,2).round(4))

condition number of matrix A is : 1.208732104844498e+18


In [ ]:
B = np.array([[1],[1],[1],[1],[1],[1]])
print('Shape of matrix B:',B.shape)
print()
B

Shape of matrix B: (6, 1)



array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
x = bicg(A,B)
print('The solution of Ax = B is :')
print()
x[0]

The solution of Ax = B is :



array([1.82159843e-13, 2.82884827e-13, 1.00000000e+00, 1.80133686e-13,
       1.49380508e-13, 1.49380508e-13])

In [ ]:
error_A = np.array([
[0,0,0,0,-0.001,0],
[0,0,0,0,0.001,0],
[0.001,0,0,0,0,0],
[0,0,0,0,0,0],
[0,0,0,0,0.001,0],
[-0.001,0,0,0,0,0],
])

print('Error for A matrix:')
print()
error_A

Error for A matrix:



array([[ 0.   ,  0.   ,  0.   ,  0.   , -0.001,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.001,  0.   ],
       [ 0.001,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.001,  0.   ],
       [-0.001,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])

In [ ]:
A_error = A + error_A

print('Matrix A after adding error:')
print()
A_error

Matrix A after adding error:



array([[2.001e+00, 1.000e+00, 1.000e+00, 1.000e+00, 9.990e-01, 1.000e+00],
       [1.000e+00, 2.001e+00, 1.000e+00, 1.000e+00, 5.000e+00, 1.000e+00],
       [1.001e+00, 1.000e+00, 1.000e+00, 2.001e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.001e+00, 1.000e+00],
       [1.000e-03, 1.000e+00, 1.000e+00, 1.000e+00, 1.001e+00, 2.001e+00],
       [0.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.001e+00]])

In [ ]:
x_A_error = bicg(A_error,B)
print('The solution of Ax = B after adding error to A is :')
print()
x_A_error[0]

The solution of Ax = B after adding error to A is :



array([ 6.06832574e-06, -1.84945151e-05,  9.99981972e-01,  6.15654093e-06,
        6.09881552e-06,  1.21336317e-05])

In [ ]:
Error_A_Error = np.linalg.norm(np.transpose(x[0]) - np.transpose(x_A_error)[0],2).round(5)
print('Error of solution when A has error:',Error_A_Error)
print()
print()

Error of solution when A has error: 3e-05




/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


In [ ]:
error_B = np.array([[0.001],[0],[-0.001],[0],[-0.001],[0.001]])
print('Error for B matrix:')
print()
error_B

Error for B matrix:



array([[ 0.001],
       [ 0.   ],
       [-0.001],
       [ 0.   ],
       [-0.001],
       [ 0.001]])

In [ ]:
B_error = B + error_B

print('Matrix B after adding error:')
print()
B_error

Matrix B after adding error:



array([[1.001],
       [1.   ],
       [0.999],
       [1.   ],
       [0.999],
       [1.001]])

In [ ]:
x_B_error = bicg(A,B_error)
print('The solution of Ax = B after adding error to B is :')
print()
x_B_error[0]

The solution of Ax = B after adding error to B is :



array([ 1.93754094e+27, -5.80294480e+27, -5.82036718e+27,  1.93754094e+27,
        1.93754094e+27,  3.87121067e+27])

In [ ]:
Error_B_Error = np.linalg.norm(np.transpose(x[0]) - np.transpose(x_B_error)[0],2).round(5)
print('Error of solution when B has error:',Error_B_Error)
print()
print()

Error of solution when B has error: 9.685004346689027e+27




In [ ]:
x_Both_error = bicg(A_error,B_error)
print('The solution of Ax = B after adding error to both A & B is :')
print()
x_Both_error[0]

The solution of Ax = B after adding error to both A & B is :



array([-1.      ,  2.996004,  4.002998, -1.      , -1.      , -1.998002])

In [ ]:
Error_both_Error = np.linalg.norm(np.transpose(x[0]) - np.transpose(x_Both_error)[0],2).round(5)
print('Error of solution when both A & B has error:',Error_both_Error)
print()
print()

Error of solution when both A & B has error: 4.9986




In [ ]:
def splitMatrix(A):
    n,m = A.shape
    if (n == m):
        diagval = np.diag(A)
        D = diags(diagval,0).toarray()
        L = (-1)*np.tril(A,-1)
        U = (-1)*np.triu(A,1)
    else:
        print("A needs to be a square matrix")
    return (L,D,U)

In [ ]:
def P_SSOR(A,w):
    L,D,U = splitMatrix(A)
    P = w/(2-w) * (1/w*D+L)*np.linalg.inv(D)*(1/w*D+L).T
    return P

In [ ]:
def myGMRES_SSOR(A,x0, b, tol, maxit):
    matrixSize = A.shape[0]
    e = np.zeros((maxit+1,1))
    rr = 1
    rstart = 2
    X = x0
    w = 1.9
    P = P_SSOR(A,w) ### preconditioned matrix
    for rs in range(0,rstart+1):
        if rr<tol:
            break
        else:
            r0 = (b-A.dot(x0))
            rho = norm(r0)
            e[0] = rho
            H = np.zeros((maxit+1,maxit))
            Qcol = np.zeros((matrixSize, maxit+1))
            Qcol[:,0:1] = r0/rho
        for k in range(1, maxit+1):
            Qcol[:,k] =np.matmul(np.matmul(A,P), Qcol[:,k-1])
            for j in range(0,k):
                H[j,k-1] = np.dot(np.transpose(Qcol[:,k]),Qcol[:,j])
                Qcol[:,k] = Qcol[:,k] - (np.dot(H[j,k-1], Qcol[:,j]))
            H[k,k-1] =norm(Qcol[:,k])
            Qcol[:,k] = Qcol[:,k]/H[k,k-1]
            n = k
            Q = np.zeros((n+1, n))
            R = np.zeros((n, n))
            R[0, 0] = norm(H[0:n+2, 0])
            Q[:, 0] = H[0:n+1, 0] / R[0,0]
            for j in range (0, n+1):
                t = H[0:n+1, j-1]
                for i in range (0, j-1):
                    R[i, j-1] = np.dot(Q[:, i], t)
                    t = t - np.dot(R[i, j-1], Q[:, i])
                R[j-1, j-1] = norm(t)
                Q[:, j-1] = t / R[j-1, j-1]

            g = np.dot(np.transpose(Q), e[0:k+1])
            Y = np.dot(np.linalg.inv(R), g)

            Res= e[0:n] - np.dot(H[0:n, 0:n], Y[0:n])
            rr = norm(Res)
            if rr < tol:
                break
        #### Updating the solution with the preconditioned matrix ####
        X = X  + np.matmul(np.matmul(P,Qcol[:, 0:k]), Y)
    return X

In [ ]:
x0 = np.zeros((6,1))
tol = 0.00001
maxit = 100
X_A_preconditioning = myGMRES_SSOR(A_error, x0, B , tol, maxit)
X_A_preconditioning

<ipython-input-21-4d8c2e25d36e>:37: RuntimeWarning: invalid value encountered in true_divide
  Q[:, j-1] = t / R[j-1, j-1]


array([[ 7.44133985e-10],
       [-2.22719532e-09],
       [ 9.99999998e-01],
       [ 7.42648083e-10],
       [ 7.43389464e-10],
       [ 1.48603913e-09]])

In [ ]:
left_Error_before_Preconditionig = np.linalg.norm(np.transpose(x[0]) - np.transpose(x_A_error)[0],2).round(5)
left_Error_After_Preconditionig =np.linalg.norm(np.transpose(x[0]) - np.transpose(X_A_preconditioning)[0],2).round(9)
print('Error Before Preconditionig:',left_Error_before_Preconditionig)
print('Error After Preconditionig:',left_Error_After_Preconditionig)
print()
print()

Error Before Preconditionig: 3e-05
Error After Preconditionig: 4e-09




In [ ]:
X_A_B_preconditioning = myGMRES_SSOR(A_error, x0, B_error , tol, maxit)
X_A_B_preconditioning

<ipython-input-21-4d8c2e25d36e>:37: RuntimeWarning: invalid value encountered in true_divide
  Q[:, j-1] = t / R[j-1, j-1]


array([[-1.      ],
       [ 2.996004],
       [ 4.002998],
       [-1.      ],
       [-1.      ],
       [-1.998002]])

In [ ]:
right_Error_before_Preconditionig = np.linalg.norm(np.transpose(x[0]) - np.transpose(x_Both_error)[0],2).round(5)
right_Error_After_Preconditionig =np.linalg.norm(np.transpose(x[0]) - np.transpose(X_A_B_preconditioning)[0],2).round(7)
print('Error Before Preconditionig:',right_Error_before_Preconditionig)
print('Error After Preconditionig:',right_Error_After_Preconditionig)
print()
print()

Error Before Preconditionig: 4.9986
Error After Preconditionig: 4.9986047




In [ ]:
A_Rectangle = np.array([
[1.001,1,1,1,1.001,1],
[1,1.001,1,1.001,1,2.999],
[1,1.001,1,1,1.001,1],
[1,1,1.001,1,1,1.001],
[3.001,1,1,1,1.001,1]
])

print('Shape of matrix A:',A_Rectangle.shape)
print()
A_Rectangle

Shape of matrix A: (5, 6)



array([[1.001, 1.   , 1.   , 1.   , 1.001, 1.   ],
       [1.   , 1.001, 1.   , 1.001, 1.   , 2.999],
       [1.   , 1.001, 1.   , 1.   , 1.001, 1.   ],
       [1.   , 1.   , 1.001, 1.   , 1.   , 1.001],
       [3.001, 1.   , 1.   , 1.   , 1.001, 1.   ]])

In [ ]:
print('condition number of matrix A is :',np.linalg.cond(A_Rectangle,2).round(4))

condition number of matrix A is : 11072.9568


In [ ]:
B_Rectangle = np.array([[1],[1],[1],[1],[1]])
print('Shape of matrix B:',B_Rectangle.shape)
print()
B_Rectangle

Shape of matrix B: (5, 1)



array([[1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
X_Rectangle = np.matmul(np.linalg.inv(np.matmul(np.transpose(A_Rectangle),A_Rectangle)),
              np.matmul(np.transpose(A_Rectangle),B_Rectangle))
print('The solution of Ax = B is :')
print()
X_Rectangle

The solution of Ax = B is :



array([[ 1.75884454e-02],
       [-1.42239947e+00],
       [ 4.00000000e+00],
       [-8.00000000e+00],
       [ 8.00000000e+00],
       [ 3.90625000e-03]])

In [ ]:
left_error_A = np.array([
[-0.001,0,0,0.002,0,0],
[0,0,0,0.001,0.009,0.001],
[0,0,0,0,0,0.008],
[0,0.002,0,0,0,0],
[0,0,0,0,0.001,0]
])
print('Error for Matrix A :')
print()
left_error_A

Error for Matrix A :



array([[-0.001,  0.   ,  0.   ,  0.002,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.001,  0.009,  0.001],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.008],
       [ 0.   ,  0.002,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.001,  0.   ]])

In [ ]:
A_left_error = A_Rectangle + left_error_A
print('Matrix A after adding Error :')
print()
A_left_error

Matrix A after adding Error :



array([[1.   , 1.   , 1.   , 1.002, 1.001, 1.   ],
       [1.   , 1.001, 1.   , 1.002, 1.009, 3.   ],
       [1.   , 1.001, 1.   , 1.   , 1.001, 1.008],
       [1.   , 1.002, 1.001, 1.   , 1.   , 1.001],
       [3.001, 1.   , 1.   , 1.   , 1.002, 1.   ]])

In [ ]:
X_left_error = np.matmul(np.linalg.inv(np.matmul(np.transpose(A_left_error),A_left_error)),
                np.matmul(np.transpose(A_left_error),B_Rectangle))
print('Solution of equation after Adding Error: ')
print()
X_left_error

Solution of equation after Adding Error: 



array([[ 2.84375   ],
       [ 2.        ],
       [-4.        ],
       [ 3.        ],
       [-0.875     ],
       [-0.00439453]])

In [ ]:
I = np.identity(6)
L = 0.005

In [ ]:
X_A_Error = np.matmul(np.linalg.inv(np.matmul(np.transpose(A_left_error),A_left_error)+ L* I),
                  np.matmul(np.transpose(A_Rectangle),B_Rectangle))
print('Solution of equation after Regularization: ')
print()
X_A_Error

Solution of equation after Regularization: 



array([[ 0.00374897],
       [ 0.59687299],
       [ 0.99582694],
       [ 0.39765578],
       [-1.00068982],
       [ 0.00406338]])

In [ ]:
Error_before_regularization = np.linalg.norm(np.transpose(X_Rectangle) - np.transpose(X_left_error),2).round(4)
Error_After_regularization = np.linalg.norm(np.transpose(X_Rectangle) - np.transpose(X_A_Error),2).round(4)
print('Error Before regularization:',Error_before_regularization)
print('Error After regularization:',Error_After_regularization)

Error Before regularization: 16.8364
Error After regularization: 12.831
